project_name: taco # also the folder name of the dataset that under data_path folder
train_set: train
val_set: val
num_gpus: 1 # Adjust this based on your available GPU(s)

# These mean and std values are commonly used for pre-trained models on ImageNet.
# You may want to calculate these specifically for your TACO dataset if it differs significantly.
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# These are default anchor scales and ratios. You might need to adjust these based on your specific object sizes.
anchors_scales: "[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]"
anchors_ratios: "[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]"

# List of object categories in your TACO dataset
obj_list:
  [
    "Trash",
    "Aerosol",
    "Aluminium blister pack",
    "Aluminium foil",
    "Battery",
    "Broken glass",
    "Carded blister pack",
    "Cigarette",
    "Clear plastic bottle",
    "Corrugated carton",
    "Crisp packet",
    "Disposable food container",
    "Disposable plastic cup",
    "Drink can",
    "Drink carton",
    "Egg carton",
    "Foam cup",
    "Foam food container",
    "Food Can",
    "Food waste",
    "Garbage bag",
    "Glass bottle",
    "Glass cup",
    "Glass jar",
    "Magazine paper",
    "Meal carton",
    "Metal bottle cap",
    "Metal lid",
    "Normal paper",
    "Other carton",
    "Other plastic",
    "Other plastic bottle",
    "Other plastic container",
    "Other plastic cup",
    "Other plastic wrapper",
    "Paper bag",
    "Paper cup",
    "Paper straw",
    "Pizza box",
    "Plastic bottle cap",
    "Plastic film",
    "Plastic glooves",
    "Plastic lid",
    "Plastic straw",
    "Plastic utensils",
    "Polypropylene bag",
    "Pop tab",
    "Rope - strings",
    "Scrap metal",
    "Shoe",
    "Single-use carrier bag",
    "Six pack rings",
    "Spread tub",
    "Squeezable tube",
    "Styrofoam piece",
    "Tissues",
    "Toilet tube",
    "Tupperware",
    "Unlabeled litter",
    "Wrapping paper",
  ]

batch_size: 4
learning_rate: 5e-4
num_epochs: 50
compound_coef: 0  # This is for EfficientDet-D0

focal_loss_alpha: 0.25
focal_loss_gamma: 2.0
